import { cn } from '@/lib/utils';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Jersey Herb Hub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'min-h-screen flex flex-col')}>
        <div className="flex items-center h-[60px] px-4 py-2 border-b-gray-200 border-b">
          Header
        </div>
        <main className="flex flex-col items-center justify-between flex-1 bg-gray-100 p-4">
          {children}
        </main>
        <div className="flex items-center h-[100px] px-4 py-2 border-t border-t-gray-200">
          Footer
        </div>
      </body>
    </html>
  );
}
